### ISSUE TITLE
Simplification: Point-Point Collision

### ISSUE THREAD

**Issue by DaveJarvis** [jeffThompson/CollisionDetection#18]
Re: https://github.com/jeffThompson/CollisionDetection/blob/master/CodeExamples/PointPoint/PointPoint.pde#L47

``` java
    if (x1 == x2 && y1 == y2) {
        return true;
    }
    return false;
```

Another sentence could introduce a further simplification:

``` java
  return x1 == x2 && y1 == y2;
```

Even though the book is for beginners, it's useful to teach slightly more advanced techniques that reduce the amount of code a person must read. Having a single exit point is still a good practice.

**Comment by treeform** [comment]
Many of the examples use this if true return true else return false pattern. I think its on pupuse.

**Comment by jeffThompson** [comment]
@DaveJarvis – thanks for the suggestion! I hear you but even for me your one-line return statement is hard to understand. It makes an implied conditional and will def be a stumbling block for a new programmer. The goal of this project is demystification so there's quite a few places where performance/tightness is lost to clarity.

The other reason they're written like that is to be easily extendable: if you wanted to return the point of collision (ex for line-line) instead of just true/false, it's now much easier to change.

Gonna close this with thanks!
