### ISSUE TITLE
Created p5.js code for intersections based on collisions 

### ISSUE THREAD

**Issue by Fillister** [jeffThompson/CollisionDetection#32]
I was working on code in p5.JS to identify intersections between objects.  I came across your most excellent CollisionDetection examples.  Subsequently using that as a template, I have written javascript code to return one or more points of intersection between objects and to draw regular polygons using only an x, y origin location, a radius and number of vertices.       

It has been a quite awhile since you developed CollisionDetection, but if you would be interested in what I came up with I am happy to give it to you.

**Comment by jeffThompson** [comment]
Hi @Fillister, thanks for the offer! I believe there's already a full port of the project into `p5.js`, though I can't seem to find it here at the moment. I would love to take the time to update this project here but it's definitely on the back burner for now!

I'm going to close this with thanks for the kind offer. If you want to publish your own version using `p5.js` you're very welcome to, so long as it follows the license!

**Comment by GoToLoop** [comment]
> I believe there's already a full port of the project into p5.js,

https://CrHallberg.com/CollisionDetection/Website/

**Comment by jeffThompson** [comment]
Super cool! The polygon examples use this idea of line segments, but the more primitive ones don't since the math is easier and the collision detection *should* be faster if you don't need the point of collision. Is your code posted somewhere? At some point it would be fantastic to add this as an advanced option for folks who want more info. (Nice diagrams too, BTW!)
